Update multi-chain permutation and permutation unittest
aqlaboratory/openfold pull request #406
Opened 2024-02-15 17:31 UTC by dingquanyu

Hi @christinaflo  and @jnwei 

Sorry I forgot to update the unittest for multi-chain permutations after the major updates on the functions. Here I have added necessary steps to prepare fake test data for testing these functions.  Now all the 3 tests can run successfully. Hope it helps.

Dingquan

2024-02-26 08:07 UTC, jnwei requested changes
Thank you so much for expanding the docstrings in multi_chain_permutation.py and for fixing the tests. 

There is a lot of non-trivial code associated with determining the best permutations, and the docstrings will go a long way towards making the code more approachable.

I have some suggestions to help further improve the clarity of the code, but overall, really nice work!

2024-03-21 13:19 UTC, dingquanyu commented
@jnwei Many thanks for your suggestions and reviews :D  I've updated the PR in the new commit

2024-04-19 09:23 UTC, jnwei requested changes
Thanks for updating the docstrings Dingquan! Just a few more minor comments

2024-04-19 09:23 UTC, jnwei commented on openfold/utils/multi_chain_permutation.py
> +def kabsch_rotation(P:torch.Tensor, Q:torch.Tensor) -> torch.Tensor:
nit: Please add spaces between arguments and type definition.

2024-04-19 09:23 UTC, jnwei commented on openfold/utils/multi_chain_permutation.py
> +                         anchor_gt_residue: list,
nit: The docstring the type is a Tensor, is this a list or a Tensor?

2024-04-19 09:23 UTC, jnwei commented on openfold/utils/multi_chain_permutation.py
> +                                anchor_gt_idx: int, anchor_gt_residue: list,
Same thing here, is anchor_gt_residue a list or a tensor?

2024-04-19 09:23 UTC, jnwei commented on tests/test_permutation.py
> +        # batch: simulates ground_truth features
nit: replace gonna with going to

2024-04-19 09:23 UTC, jnwei commented on tests/test_permutation.py
>          possible_outcome = [[(0, 1), (1, 0), (2, 3), (3, 4), (4, 2)], [(0, 0), (1, 1), (2, 3), (3, 4), (4, 2)]]
Just a reminder here, a comment explaining why you expect the given possible outcome, and why the wrong_outcome is bad would be very helpful.

To help explain the examples, you could even break up the examples into different variables with acceptable / not acceptable cases. For example:

```
chain_a_permuted = [(0, 1), (1, 0), (2, 2), (3, 3), (4, 4)]
chain_b_permuted = [(0, 0), (1, 1), (2, 3), (3, 4), (4, 2)]
chains_a_and_b_permuted = [(0, 1), (1, 0), (2, 3), (3, 4), (4, 2)]
no_permutation = [(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]

possible_outcome = [chain_a_permuted, chain_b_permuted]
wrong_outcome = [chain_a_and_b_permuted, no_permutation] 
```

Although in this example, I still don't understand why `chain_a_and_b_permuted` would be under `wrong_outcome`

2024-05-11 08:37 UTC, jnwei approved these changes

2024-05-11 08:37 UTC, jnwei commented
Thanks for the additions to the docstring Dingquan! The explanation for the tests are much clearer now.

2024-05-11 09:02 UTC, merged